import { Card, CardContent } from "@/components/ui/card";
import { Star, Quote } from "lucide-react";

const testimonials = [
  {
    name: "Daniel Reed",
    role: "Ad Agency Owner",
    content: "For anyone in advertising, this is a game changer. It saves me so much time. The Ads come out clean and has increased our speed. Fantastic for agencies looking to scale their creative output!",
    rating: 5
  },
  {
    name: "Sarah Johnson",
    role: "Marketing Director",
    content: "The AI-generated creatives are incredible. Our CTR increased by 45% within the first month. The auto-posting feature is a lifesaver for our social media management.",
    rating: 5
  },
  {
    name: "Mike Chen",
    role: "E-commerce Owner",
    content: "Product ads generated by Amealio convert amazingly well. The variety of formats and the quality of output consistently exceeds our expectations.",
    rating: 5
  }
];

const TestimonialSection = () => {
  return (
    <section className="py-24 bg-muted/30" style={{ fontFamily: 'Inter, sans-serif' }}>
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4" style={{ color: '#001D51' }}>
            What our{" "}
            <span style={{ color: '#001D51' }}>
              customers say
            </span>
          </h2>
          <p className="text-xl" style={{ color: '#777777' }}>
            Join thousands of satisfied users who've transformed their marketing
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <Card 
              key={testimonial.name} 
              className="border-0 bg-card/80 backdrop-blur-sm hover:shadow-feature transition-all duration-300"
            >
              <CardContent className="p-8">
                <div className="mb-4">
                  <Quote className="w-8 h-8 text-primary opacity-50" />
                </div>
                
                <div className="flex items-center mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 text-accent-orange fill-current" />
                  ))}
                </div>

                <p className="mb-6 leading-relaxed" style={{ color: '#001D51' }}>
                  "{testimonial.content}"
                </p>

                <div className="border-t border-border pt-4">
                  <div className="font-semibold" style={{ color: '#001D51' }}>
                    {testimonial.name}
                  </div>
                  <div className="text-sm" style={{ color: '#777777' }}>
                    {testimonial.role}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};

export default TestimonialSection;